{
  "name": "Nightland",
  "number": 1,
  "world_index": 0,
  "ship_pos": "3,3,0",
  "cells": [
    {
      "tile": {
        "pos": "2,0,0",
        "size": "2,2,6",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "1,0,6",
        "size": "4,2,100",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "-2,0,6",
        "size": "2,2,100",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "6,0,6",
        "size": "2,2,100",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "-2,3,10",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "6,3,10",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "-2,3,30",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "6,3,30",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "-2,3,50",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "6,3,50",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "-2,3,70",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "6,3,70",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "-2,3,90",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "6,3,90",
        "size": "2,1,10",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "1,2,106",
        "size": "4,2,40",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "1,4,146",
        "size": "4,2,80",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "1,6,186",
        "size": "1.5,6,40",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "3.5,6,186",
        "size": "1.5,6,40",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "2.5,4,226",
        "size": "1,2,40",
        "preset": 2
      }
    },
    {
      "tunnel": {
        "pos": "3,6,226",
        "depth": 40,
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "1,4,266",
        "size": "4,2,40",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "1,0,336",
        "size": "1.5,2,20",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "3.5,0,336",
        "size": "1.5,2,20",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "1,-4,386",
        "size": "1.5,2,20",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "3.5,-4,386",
        "size": "1.5,2,20",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "1,-8,436",
        "size": "4,2,80",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "1,-6,516",
        "size": "4,8,80",
        "preset": 0
      }
    },
    {
      "tile": {
        "pos": "-2,-8,506",
        "size": "3,2,110",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "5,-8,506",
        "size": "3,2,110",
        "preset": 1
      }
    },
    {
      "tile": {
        "pos": "1,-8,596",
        "size": "4,2,80",
        "preset": 2
      }
    },
    {
      "tile": {
        "pos": "2.5,-8,676",
        "size": "1,2,40",
        "preset": 2
      }
    },
    {
      "tunnel": {
        "pos": "3,-6,676",
        "depth": 40,
        "preset": 0,
        "end": true
      }
    },
    {
      "finish": {
        "pos": "3,-6,716",
        "radius": 1
      }
    }
  ]
 }